#!/usr/bin/env bash

source $(dirname $0)/env

mkdir -p ~/.cache/{npm,pip,apk}
docker build -f Dockerfile \
             -t ${IMAGE_NAME}:latest \
             -v ~/.cache/npm:/root/.npm \
             -v ~/.cache/pip:/root/.cache/pip \
             -v ~/.cache/apk:/etc/apk/cache \
