#!/usr/bin/env bash

if [ -z ${AWS_ACCESS_KEY_ID+x} ]; then
  ACCESS_KEY=$(awk '/aws_access_key_id/ {print $3;exit}' ~/.aws/credentials)
fi

if [ -z ${AWS_SECRET_ACCESS_KEY+x} ]; then
  SECRET_KEY=$(awk '/aws_secret_access_key/ {print $3;exit}' ~/.aws/credentials)
fi

if [ -z ${AWS_DEFAULT_REGION+x} ]; then
  REGION="ap-southeast-2"
fi

if ! docker image ls --all | grep -q localhost/cdk; then
  ./build
else
  CREATED=$(docker images --format json  | jq '.[] | select(.Names == ["localhost/cdk:latest"]).Created')
  echo "Using CDK image created ${CREATED}."
fi

docker run --rm \
           -it \
           -v $(pwd):/app \
           -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-$ACCESS_KEY} \
           -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-$SECRET_KEY} \
           -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-$REGION} \
           localhost/cdk:latest \
           "$@" 
