#!/usr/bin/env bash

docker run --rm \
           -v $(pwd):/app \
           localhost/cdk:latest \
           -e AWS_ACCESS_KEY_ID \
           -e AWS_SECRET_ACCESS_KEY \
           -e AWS_SESSION_TOKEN \
           -e AWS_DEFAULT_REGION \
           "$@" 
