#!/usr/bin/env bash

source $(dirname $0)/env

if ! docker image ls --all | grep -q ${IMAGE_NAME}; then
  ./build
else
  CREATED=$(docker images --format json  | jq --arg IMAGE ${IMAGE_NAME}:${IMAGE_VERSION} '.[] | select(.Names == [$IMAGE]).Created')
  echo "Using CDK image created ${CREATED}."
fi

docker run --rm \
           -it \
           --network host \
           -v $(pwd):/app \
           -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-$ACCESS_KEY} \
           -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-$SECRET_KEY} \
           -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-$REGION} \
           -e GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-$GIT_NAME} \
           -e GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-$GIT_EMAIL} \
           -e GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME:-$GIT_NAME} \
           -e GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL:-$GIT_EMAIL} \
           -e DOCKER_HOST="tcp://${HOST_IP}:${HOST_PORT}" \
           ${IMAGE_NAME}:${IMAGE_VERSION} \
           "$@" 
