FROM cdk-docker-base:latest

RUN --mount=type=cache,target=/root/.npm \
  npm -g install aws-cdk@2.27.0

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip \
    && cd /tmp \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm /tmp/awscliv2.zip
