#!/usr/bin/env bash
cd "$(dirname $0)/.."
source environment

./scripts/build-cli

if [ ! -f requirements.cdk.txt ]; then
  touch requirements.cdk.txt
fi

docker build \
  -f Dockerfile.cdk \
  -t ${IMAGE_NAME}:latest \
  .
