#!/usr/bin/env bash

cd "$(git rev-parse --show-toplevel)" || exit
source scripts/set-env

docker build \
  --build-arg CDK_VERSION="$CDK_VERSION" \
  --build-arg DOCKER_VERSION="$DOCKER_VERSION" \
  --build-arg NODE_VERSION="$NODE_VERSION" \
  --build-arg PIP_VERSION="$PIP_VERSION" \
  --build-arg POETRY_VERSION="$POETRY_VERSION" \
  --file Dockerfile \
  --tag cdk-docker:latest \
  .
