#!/usr/bin/env bash
cd "$(git rev-parse --show-toplevel)" || exit

docker run --rm \
           -it \
           --network host \
           -v "$(pwd)":"$(pwd)" \
           -w "$(pwd)" \
           -e AWS_ACCESS_KEY_ID \
           -e AWS_SECRET_ACCESS_KEY \
           -e AWS_DEFAULT_REGION \
           -e GIT_AUTHOR_NAME \
           -e GIT_AUTHOR_EMAIL \
           -e GIT_COMMITTER_NAME \
           -e GIT_COMMITTER_EMAIL \
           "${DOCKER_OPTS}" \
           "${IMAGE_NAME}:${IMAGE_VERSION}" \
           "${@:-"bash"}"
