#!/usr/bin/env bash
cd "$(dirname $0)/.."
source environment

# ./scripts/build-cdk

docker run --rm \
           -it \
           --network host \
           -v $(pwd):$(pwd) \
           -w $(pwd) \
           -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-$ACCESS_KEY} \
           -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-$SECRET_KEY} \
           -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-$REGION} \
           -e GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-$GIT_NAME} \
           -e GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-$GIT_EMAIL} \
           -e GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME:-$GIT_NAME} \
           -e GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL:-$GIT_EMAIL} \
           ${DOCKER_OPTS} \
           ${IMAGE_NAME}:${IMAGE_VERSION} \
           ${@:-"bash"}
