#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

export DOCKER_BUILDKIT=1

# renovate: datasource=pypi depName=aws-cdk-lib
export CDK_VERSION="2.176.0"
# renovate: datasource=docker depName=docker versioning=docker
export DOCKER_VERSION="27.5.0"
 # renovate: datasource=github-tags depName=nodejs/node versioning=node
export NODE_VERSION="22.13.1"
# renovate: datasource=pypi depName=pip
export PIP_VERSION="24.3.1"
# renovate: datasource=pypi depName=poetry
export POETRY_VERSION="2.0.1"
