#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

export DOCKER_BUILDKIT=1

# renovate: datasource=pypi depName=aws-cdk-lib
export CDK_VERSION="2.147.2"
# renovate: datasource=docker depName=docker versioning=docker
export DOCKER_VERSION="27.0.2"
 # renovate: datasource=github-tags depName=nodejs/node versioning=node
export NODE_VERSION="20.15.0"
# renovate: datasource=pypi depName=pip
export PIP_VERSION="24.1.1"
# renovate: datasource=pypi depName=poetry
export POETRY_VERSION="1.8.3"
