#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

# renovate: datasource=pypi depName=aws-cdk-lib
CDK_VERSION="2.100.0"
# renovate: datasource=github-tags depName=docker/cli
DOCKER_VERSION="24.0.6"
# renovate: datasource=node-version
NODE_VERSION="18.18.2"
# renovate: datasource=pypi depName=pip
PIP_VERSION="23.3.1"
# renovate: datasource=pypi depName=poetry
POETRY_VERSION="1.6.1"

{
  echo "CDK_VERSION=$CDK_VERSION";
  echo "DOCKER_VERSION=$DOCKER_VERSION";
  echo "NODE_VERSION=$NODE_VERSION";
  echo "PIP_VERSION=$PIP_VERSION";
  echo "POETRY_VERSION=$POETRY_VERSION";
} >> "$GITHUB_ENV"
