#!/usr/bin/env bash
cd "$(dirname $0)/.."
source environment

./scripts/build-base

docker run --rm \
           -it \
           --network host \
           -v $(pwd):$(pwd) \
           -w $(pwd) \
           ${DOCKER_OPTS} \
           ${IMAGE_NAME}-base:${IMAGE_VERSION} \
           ${UPGRADE_CMD}
