name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

#      - name: "Hadolint"
#        uses: hadolint/hadolint-action@v3.1.0

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Set versions"
        run: scripts/set_github_env

      - name: "Build and push"
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            "CDK_VERSION=${{ env.CDK_VERSION }}"
            "DOCKER_VERSION=${{ env.DOCKER_VERSION }}"
            "NODE_VERSION=${{ env.NODE_VERSION }}"
            "PIP_VERSION=${{ env.PIP_VERSION }}"
            "POETRY_VERSION=${{ env.POETRY_VERSION }}"
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.CDK_VERSION }}
