name: Check

on:
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Hadolint"
        uses: hadolint/hadolint-action@v3.1.0

      - name: "Shellcheck"
        run: shellcheck scripts/*

  dry-run:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Set versions"
        run: scripts/set-github-env

      - name: "Build dry run"
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            "CDK_VERSION=${{ env.CDK_VERSION }}"
            "DOCKER_VERSION=${{ env.DOCKER_VERSION }}"
            "NODE_VERSION=${{ env.NODE_VERSION }}"
            "PIP_VERSION=${{ env.PIP_VERSION }}"
            "POETRY_VERSION=${{ env.POETRY_VERSION }}"
          push: false
          tags: ghcr.io/${{ github.repository }}:${{ env.CDK_VERSION }}-${{ github.run_number }}
