---
name: Lint

on:
  workflow_call:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Shellcheck"
        run: shellcheck scripts/*
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Hadolint"
        uses: hadolint/hadolint-action@v3.1.0
